# Generated by Django 4.2.6 on 2023-10-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('group', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_messages',
            field=models.ManyToManyField(blank=True, related_name='group', to='group.groupmessage'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='group_posts', to='post.post'),
        ),
    ]
